services:
  app:
    container_name: pos-api-app
    build:
      context: .
      dockerfile: Dockerfile
    image: pos-api
    ports:
      - "8054:80"
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - pos-api-network
    environment:
      - LC_ALL=tr_TR.UTF-8
      - LANG=tr_TR.UTF-8

  db:
    image: mysql:8.0
    container_name: pos-api-db
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pos-api-db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: root
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3354:3306"
    networks:
      - pos-api-network

networks:
  pos-api-network:

volumes:
  mysql-data:
